#!/bin/bash

echo "🕊️ Chofetz Chaim App - Firebase Setup"
echo "======================================"
echo ""
echo "This script will help you set up Firebase for your app."
echo ""
echo "📋 Prerequisites:"
echo "  1. Google/Gmail account"
echo "  2. Web browser"
echo ""
echo "Let's get started!"
echo ""

# Open Firebase Console
echo "Step 1: Opening Firebase Console..."
echo "Please:"
echo "  1. Sign in with your Google account"
echo "  2. Click 'Add project' or 'Create a project'"
echo "  3. Name it: 'chofetz-chaim-app'"
echo "  4. Disable Google Analytics (optional)"
echo "  5. Click 'Create project'"
echo ""
read -p "Press Enter when you've created your project..."

# Instructions for Auth
echo ""
echo "Step 2: Enable Authentication"
echo "In Firebase Console:"
echo "  1. Click 'Authentication' in left sidebar"
echo "  2. Click 'Get started'"
echo "  3. Click 'Email/Password'"
echo "  4. Toggle 'Enable'"
echo "  5. Click 'Save'"
echo ""
read -p "Press Enter when Authentication is enabled..."

# Instructions for Firestore
echo ""
echo "Step 3: Enable Firestore Database"
echo "In Firebase Console:"
echo "  1. Click 'Firestore Database' in left sidebar"
echo "  2. Click 'Create database'"
echo "  3. Select 'Start in test mode'"
echo "  4. Choose your region (closest to you)"
echo "  5. Click 'Enable'"
echo ""
read -p "Press Enter when Firestore is enabled..."

# Get config
echo ""
echo "Step 4: Get Your Firebase Configuration"
echo "In Firebase Console:"
echo "  1. Click the gear icon (⚙️) next to 'Project Overview'"
echo "  2. Click 'Project settings'"
echo "  3. Scroll to 'Your apps'"
echo "  4. Click the Web icon (</>) to add a web app"
echo "  5. Register app nickname: 'Chofetz Chaim Web'"
echo "  6. Don't check 'Firebase Hosting'"
echo "  7. Click 'Register app'"
echo "  8. COPY the firebaseConfig object"
echo ""
echo "Your config looks like this:"
echo ""
echo "const firebaseConfig = {"
echo "  apiKey: \"AIzaSyA...\","
echo "  authDomain: \"your-project.firebaseapp.com\","
echo "  projectId: \"your-project-id\","
echo "  storageBucket: \"your-project.appspot.com\","
echo "  messagingSenderId: \"123456789\","
echo "  appId: \"1:123:web:abc123\""
echo "};"
echo ""
read -p "Press Enter when you have copied your config..."

# Instructions for updating config file
echo ""
echo "Step 5: Update Your App Configuration"
echo ""
echo "Now open this file in your editor:"
echo "  public/firebase-config.js"
echo ""
echo "Replace the placeholder config with YOUR actual config."
echo ""
echo "⚠️  Important: Don't commit your Firebase config to public repositories!"
echo ""
read -p "Press Enter when you've updated the config file..."

# Security Rules
echo ""
echo "Step 6: Set Up Security Rules (Optional but Recommended)"
echo ""
echo "In Firebase Console:"
echo "  1. Go to Firestore Database"
echo "  2. Click 'Rules' tab"
echo "  3. Replace with the rules from FIREBASE_SETUP.md"
echo "  4. Click 'Publish'"
echo ""
read -p "Press Enter to continue..."

# Final steps
echo ""
echo "✅ Setup Complete!"
echo ""
echo "Your app is now connected to Firebase!"
echo ""
echo "🚀 Next Steps:"
echo "  1. Start your server: npm run dev"
echo "  2. Open http://localhost:3000"
echo "  3. Sign up with a test account"
echo "  4. Start chatting!"
echo ""
echo "📚 For detailed documentation, see:"
echo "  - FIREBASE_SETUP.md"
echo "  - SETUP_INSTRUCTIONS.md"
echo ""
echo "🎉 Enjoy your Chofetz Chaim app!"
